#version: '3.8'

services:
  # ClickHouse Database
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "9001:9000"
      - "8124:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./docker/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DATABASE:-analytics}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL for Airflow metadata
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-airflow}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Airflow Celery
  redis:
    image: redis:7-alpine
    container_name: redis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Airflow Common
  airflow-common: &airflow-common
    image: apache/airflow:2.9.1
    environment: &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres/${POSTGRES_DB:-airflow}
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
      _PIP_ADDITIONAL_REQUIREMENTS: 'clickhouse-connect==0.7.0 aiohttp==3.9.2 tenacity==8.2.3 pydantic==2.5.0 python-dotenv==1.0.0 python-json-logger==2.0.7 httpx==0.26.0 orjson==3.10.11 pendulum==3.0.0 aiofiles==24.1.0 SPARQLWrapper>=2.0.0'
      PIP_PREFER_BINARY: '1'
      PIP_ONLY_BINARY: 'orjson'
      # Custom environment variables
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_HTTP_PORT: 8123
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE}
      MINIO_ENDPOINT: minio:9002
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_BUCKET: ${MINIO_BUCKET:-raw-data}
      # API Keys from .env file
      DESTATIS_API_KEY: ${DESTATIS_API_KEY}
      DAWUM_API_KEY: ${DAWUM_API_KEY}
      EUROSTAT_API_KEY: ${EUROSTAT_API_KEY}
      GESIS_API_KEY: ${GESIS_API_KEY}
      SOEP_API_KEY: ${SOEP_API_KEY}
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
      - ${AIRFLOW_PROJ_DIR:-.}/connectors:/opt/airflow/connectors
      - ${AIRFLOW_PROJ_DIR:-.}/elt:/opt/airflow/elt
      - ${AIRFLOW_PROJ_DIR:-.}/scraping:/opt/airflow/scraping
      - ${AIRFLOW_PROJ_DIR:-.}/requirements.txt:/requirements.txt
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  # Airflow Webserver
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    container_name: airflow-webserver
    ports:
      - "${AIRFLOW_WEBSERVER_PORT:-8081}:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  # Airflow Scheduler
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow-scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  # Airflow Initialization
  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''  # Disable pip installs for init container
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources

  # MinIO S3-compatible Object Storage
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9003:9001"
      - "9002:9002"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001" --address ":9002"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # dbt CLI Container
  dbt:
    build: 
      context: .
      dockerfile: Dockerfile.dbt
    container_name: dbt
    volumes:
      - ./dbt_project:/usr/app/dbt_project
      - ./data:/usr/app/data
    depends_on:
      - clickhouse
    environment:
      - DBT_PROFILES_DIR=/usr/app/dbt_project
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000  # Internal Docker network port
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=asjrh25423sfa#+43qw56j
      - CLICKHOUSE_DATABASE=analytics
    command: ["tail", "-f", "/dev/null"]  # Keep container running

  # Jupyter Notebook for analysis
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
      - ./dbt_project:/home/jovyan/work/dbt_project
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=admin
    depends_on:
      - clickhouse

volumes:
  clickhouse_data:
  postgres_data:
  minio_data:
