name: bnb_data4transformation
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.12
  
  # Core Data & Analytics
  - pandas>=2.1.0
  - numpy>=1.25.0
  - pyarrow>=14.0.0
  - polars>=0.20.0
  
  # HTTP & Async
  - aiohttp>=3.9.0
  - httpx>=0.26.0
  - requests>=2.31.0
  - aiofiles>=24.1.0
  
  # Validation & Configuration
  - pydantic>=2.5.0
  - python-dotenv>=1.0.0
  - tenacity>=8.2.0
  
  # CLI & Rich output
  - typer>=0.9.0
  - rich>=13.0.0
  
  # Web Scraping
  - beautifulsoup4>=4.12.0
  - scrapy>=2.11.0
  - selenium>=4.17.0
  
  # Testing
  - pytest>=7.4.0
  - pytest-asyncio>=0.21.0
  - pytest-cov>=4.0.0
  
  # Code Quality
  - black>=24.0.0
  - ruff>=0.6.0
  - isort>=5.13.0
  - mypy>=1.8.0
  - pre-commit>=3.8.0
  
  # Scientific Computing
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - scikit-learn>=1.4.0
  - scipy>=1.13.0
  - jupyterlab>=4.0.0
  - ipykernel>=6.28.0
  
  # Development
  - pip>=24.0
  
  # Install via pip (packages not available in conda-forge or requiring specific versions)
  - pip:
      # Apache Airflow & Providers
      - apache-airflow==2.9.1
      - apache-airflow-providers-postgres>=5.10.0
      - apache-airflow-providers-http>=4.10.0
      - apache-airflow-providers-celery>=3.10.0
      - apache-airflow-providers-common-sql>=1.26.0
      - apache-airflow-providers-slack>=9.0.0
      
      # Database Connectors
      - clickhouse-connect>=0.7.0
      - psycopg2-binary>=2.9.9
      - sqlalchemy>=1.4.0
      
      # Object Storage
      - minio>=7.2.0
      - boto3>=1.34.0
      
      # Data Processing
      - orjson>=3.9.0
      - pendulum>=3.0.0
      
      # Monitoring & Logging
      - structlog>=23.2.0
      - python-json-logger>=2.0.7
      - prometheus-client>=0.19.0
      
      # Statistics APIs
      - pystatis>=0.5.0
      
      # Additional utilities found in codebase
      - flask>=2.2.0
      - celery>=5.5.0
      - redis>=5.0.0
