name: 'bnb_data4transformation'
version: '1.0.0'

profile_template:
  renderer: jinja
  required_vars: ['host', 'port', 'user', 'password', 'database']

prompts:
  host:
    type: 'text'
    hint: 'hostname (without "http://" or "https://")'
    when: '{{ not env_var("CLICKHOUSE_HOST") }}'
    default: 'localhost'
  
  port:
    type: 'int'
    hint: 'port (usually 8123 for HTTP or 9000 for native)'
    when: '{{ not env_var("CLICKHOUSE_PORT") }}'
    default: 9000
  
  user:
    type: 'text'
    hint: 'username'
    when: '{{ not env_var("CLICKHOUSE_USER") }}'
    default: 'admin'
  
  password:
    type: 'password'
    hint: 'password'
    when: '{{ not env_var("CLICKHOUSE_PASSWORD") }}'
    default: 'admin123'
  
  database:
    type: 'text'
    hint: 'database name'
    when: '{{ not env_var("CLICKHOUSE_DATABASE") }}'
    default: 'bnb_data'

outputs:
  dev:
    type: clickhouse
    host: '{{ env_var("CLICKHOUSE_HOST", "localhost") }}'
    port: '{{ env_var("CLICKHOUSE_PORT", 9000) | int }}'
    user: '{{ env_var("CLICKHOUSE_USER", "admin") }}'
    password: '{{ env_var("CLICKHOUSE_PASSWORD", "asjrh25423sfa#+43qw56j") }}'
    database: '{{ env_var("CLICKHOUSE_DATABASE", "analytics") }}'
    schema: dev
    secure: false
    verify: false
    connect_timeout: 10
    send_receive_timeout: 300
    sync_request_timeout: 5
    compress_block_size: 1048576
    compression: lz4
    
  prod:
    type: clickhouse
    host: '{{ env_var("CLICKHOUSE_HOST_PROD", "localhost") }}'
    port: '{{ env_var("CLICKHOUSE_PORT_PROD", 9000) | int }}'
    user: '{{ env_var("CLICKHOUSE_USER_PROD", "admin") }}'
    password: '{{ env_var("CLICKHOUSE_PASSWORD_PROD", "asjrh25423sfa#+43qw56j") }}'
    database: '{{ env_var("CLICKHOUSE_DATABASE_PROD", "analytics") }}'
    schema: prod
    secure: true
    verify: true
    connect_timeout: 10
    send_receive_timeout: 300
    sync_request_timeout: 5
    compress_block_size: 1048576
    compression: lz4
  
  ci:
    type: clickhouse
    host: '{{ env_var("CLICKHOUSE_HOST_CI", "localhost") }}'
    port: '{{ env_var("CLICKHOUSE_PORT_CI", 9000) | int }}'
    user: '{{ env_var("CLICKHOUSE_USER_CI", "admin") }}'
    password: '{{ env_var("CLICKHOUSE_PASSWORD_CI", "asjrh25423sfa#+43qw56j") }}'
    database: '{{ env_var("CLICKHOUSE_DATABASE_CI", "analytics_ci") }}'
    schema: ci
    secure: false
    verify: false
    connect_timeout: 10
    send_receive_timeout: 300
    sync_request_timeout: 5
    compress_block_size: 1048576
    compression: lz4

target: dev
