name: 'bnb_data4transformation'
version: '1.0.0'

profile_template:
  renderer: jinja
  required_vars: ['host', 'port', 'user', 'password', 'database']

prompts:
  host:
    type: 'text'
    hint: 'hostname (without "http://" or "https://")'
    when: '{{ not env_var("CLICKHOUSE_HOST") }}'
    default: 'localhost'
  
  port:
    type: 'int'
    hint: 'port (usually 8123 for HTTP or 9000 for native)'
    when: '{{ not env_var("CLICKHOUSE_PORT") }}'
    default: 8123
  
  user:
    type: 'text'
    hint: 'username'
    when: '{{ not env_var("CLICKHOUSE_USER") }}'
    default: 'default'
  
  password:
    type: 'password'
    hint: 'password'
    when: '{{ not env_var("CLICKHOUSE_PASSWORD") }}'
    default: ''
  
  database:
    type: 'text'
    hint: 'database name'
    when: '{{ not env_var("CLICKHOUSE_DATABASE") }}'
    default: 'political_data'

outputs:
  dev:
    type: clickhouse
    host: '{{ env_var("CLICKHOUSE_HOST", "localhost") }}'
    port: '{{ env_var("CLICKHOUSE_PORT", 8123) | int }}'
    user: '{{ env_var("CLICKHOUSE_USER", "default") }}'
    password: '{{ env_var("CLICKHOUSE_PASSWORD", "") }}'
    database: '{{ env_var("CLICKHOUSE_DATABASE", "political_data") }}'
    schema: dev
    secure: false
    verify: false
    connect_timeout: 10
    send_receive_timeout: 300
    sync_request_timeout: 5
    compress_block_size: 1048576
    compression: lz4
    
  prod:
    type: clickhouse
    host: '{{ env_var("CLICKHOUSE_HOST_PROD", "localhost") }}'
    port: '{{ env_var("CLICKHOUSE_PORT_PROD", 8123) | int }}'
    user: '{{ env_var("CLICKHOUSE_USER_PROD", "default") }}'
    password: '{{ env_var("CLICKHOUSE_PASSWORD_PROD", "") }}'
    database: '{{ env_var("CLICKHOUSE_DATABASE_PROD", "political_data") }}'
    schema: prod
    secure: true
    verify: true
    connect_timeout: 10
    send_receive_timeout: 300
    sync_request_timeout: 5
    compress_block_size: 1048576
    compression: lz4
  
  ci:
    type: clickhouse
    host: '{{ env_var("CLICKHOUSE_HOST_CI", "localhost") }}'
    port: '{{ env_var("CLICKHOUSE_PORT_CI", 8123) | int }}'
    user: '{{ env_var("CLICKHOUSE_USER_CI", "default") }}'
    password: '{{ env_var("CLICKHOUSE_PASSWORD_CI", "") }}'
    database: '{{ env_var("CLICKHOUSE_DATABASE_CI", "political_data_ci") }}'
    schema: ci
    secure: false
    verify: false
    connect_timeout: 10
    send_receive_timeout: 300
    sync_request_timeout: 5
    compress_block_size: 1048576
    compression: lz4

target: dev
